export const profile = {
  name: "Heidi Herzog",
  firstName: "Heidi",
  lastName: "Herzog",
  title: "Contract Analyst",
  location: "Houston",
  linkedin: "https://www.linkedin.com/in/heidi-herzog",
  about:
    "Communication graduate from UT Austin. Works in contract administration in Houston energy, with internships in contracts, PR, and marketing.",
  experience: [
    {
      role: "Associate Analyst, Contract Administration",
      org: "Energy Transfer",
      dates: "Oct 2025 – Present",
      place: "Houston",
      logo: "/assets/logos/energy-transfer.png",
      logoAlt: "Energy Transfer logo",
      current: true,
    },
    {
      role: "Contract Analyst Intern",
      org: "Twin Eagle",
      dates: "May 2025 – Oct 2025",
      place: "Houston",
      logo: "/assets/logos/twin-eagle.png",
      logoAlt: "Twin Eagle logo",
    },
    {
      role: "Intern",
      org: "The PR Boutique Texas",
      dates: "Jun 2024 – Aug 2024",
      place: "Austin",
      logo: "/assets/logos/pr-boutique.png",
      logoAlt: "The PR Boutique logo",
    },
    {
      role: "Sales and Marketing Intern",
      org: "ARC Document Solutions",
      dates: "Jun 2023 – Aug 2023",
      place: "Houston",
      logo: "/assets/logos/arc.png",
      logoAlt: "ARC Document Solutions logo",
    },
    {
      role: "Legal Videographer",
      org: "RealTime Media",
      dates: "May 2022 – Aug 2022",
      place: "Houston",
      logo: "/assets/logos/realtime-media.svg",
      logoAlt: "RealTime Media monogram",
    },
  ],
  education: {
    school: "The University of Texas at Austin",
    focus: "Communication",
    dates: "Aug 2021 – May 2025",
    mark: "/assets/logos/ut-mark.png",
    wordmark: "/assets/logos/ut-austin.svg",
  },
} as const;
